---
title: Your Comic Title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
tab_title: Your Comic!
email: 
description: Here's the description of your comic!
url: https://peahatlanding.github.io/Plain-Webcomic/
twitter_username: http://twitter.com/peahat
tumblr_username: http://peahat.tumblr.com
patreon_username: peahat
author_twitter_username: 
author_tumblr_username: 
author_patreon_username: 
markdown: kramdown
theme: minima
